export const data = {
  products: [
    {
      _id: "1",
      name: "Everyday Tube Top Ribbed",
      slug: "everyday-tube-top-ribbed",
      image: "/img/1.jpg",
      price: 180.0,
      brand: "Brand A",
      description: "A nice ribbed top for everyday wear.",
      category: "Tops",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      colors: ["#000000", "#FFFFFF", "#FF0000"],
      sizes: ["S", "M", "L"],
    },
    {
      _id: "2",
      name: "Everyday Tube Top Ribbed",
      slug: "everyday-tube-top-1",
      image: "/img/2.jpg",
      price: 180.0,
      brand: "Brand A",
      description: "A nice ribbed top for everyday wear.",
      category: "Tops",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      colors: ["#000000", "#FFFFFF", "#FF0000"],
      sizes: ["S", "M", "L"],
    },
    {
      _id: "3",
      name: "Everyday Tube Top Ribbed",
      slug: "everyday-tube-3",
      image: "/img/3.jpg",
      price: 180.0,
      brand: "Brand A",
      description: "A nice ribbed top for everyday wear.",
      category: "Tops",
      rating: 4.5,
      numReviews: 10,
      countInStock: 5,
      colors: ["#000000", "#FFFFFF", "#FF0000"],
      sizes: ["S", "M", "L"],
    },
  ],
};
